/**
 * Compliance Engine
 * Generates structured, audit-ready compliance reports for food batches.
 */

/**
 * Generate a full compliance report for a batch
 * @param {Object} batch - Batch document from MongoDB
 * @param {Object} donor - User document (donor info)
 * @returns {Object} Structured compliance report
 */
function generateComplianceReport(batch, donor) {
  return {
    reportId: `RPT-${batch.batchId}`,
    generatedAt: new Date().toISOString(),
    batch: {
      batchId: batch.batchId,
      status: batch.status,
      createdAt: batch.createdAt,
    },
    donor: {
      businessName: donor.businessName,
      businessType: donor.businessType,
      location: donor.location,
      email: donor.email,
    },
    foodDetails: {
      category: batch.category,
      quantity: batch.quantity,
      preparationTime: batch.preparationTime,
      expiryTime: batch.expiryTime,
    },
    riskAssessment: {
      riskLevel: batch.riskLevel,
      classification: getRiskDescription(batch.riskLevel),
    },
    costEstimate: {
      costPerMeal: batch.costPerMeal,
      totalValue: batch.totalValue,
    },
    proof: {
      imageUrl: batch.imageUrl,
      timestamp: batch.createdAt,
      immutable: true,
    },
    complianceStatus: 'COMPLIANT',
    disclaimer:
      'This report is auto-generated by the Taumoeba Filter Compliance Engine. All batch records are immutable after creation and serve as audit-ready documentation.',
  };
}

/**
 * Get human-readable risk description
 */
function getRiskDescription(level) {
  switch (level) {
    case 'LOW':
      return 'Food is within safe consumption window. Low risk of spoilage.';
    case 'MEDIUM':
      return 'Food is approaching expiry. Medium risk — expedite distribution.';
    case 'HIGH':
      return 'Food has exceeded or is near safe window. High risk — immediate action required.';
    default:
      return 'Unknown risk level.';
  }
}

module.exports = { generateComplianceReport, getRiskDescription };
