/**
 * Risk Modeling Agent (RMA)
 * 
 * Specialized agent that computes the final risk assessment for a food batch.
 * Unlike the original monolithic risk engine, this agent considers MULTIPLE
 * inputs from other agents (DVA warnings + VAA confidence) to produce a
 * more nuanced, adjusted risk score.
 * 
 * Responsibilities:
 * - Compute baseline food safety risk from category + preparation time
 * - Apply risk modifiers based on DVA warnings (caution factors)
 * - Apply risk modifiers based on VAA image confidence
 * - Calculate cost estimation
 * - Return comprehensive risk assessment with full modifier transparency
 * 
 * Design: The RMA demonstrates "agent reasoning" — it doesn't just calculate;
 * it adjusts its output based on intelligence gathered by other agents.
 */

const AgentError = require('./AgentError');

// Safe consumption window (hours) by food category
// Mirrors the original riskEngine but is now part of the agent ecosystem
const SAFE_WINDOWS = {
  bread:  4,    // Dry food — longest window
  snacks: 4,    // Dry food
  fruits: 3,    // Fresh but not cooked
  veg:    3,    // Cooked vegetables
  dal:    2.5,  // Cooked lentils
  rice:   2,    // Cooked rice — bacteria-prone
  mixed:  2,    // Mixed dishes — conservative estimate
  curry:  1,    // Perishable curry
  dairy:  1,    // Dairy products — highly perishable
  other:  2,    // Default fallback
};

// Risk modifier configurations
const RISK_MODIFIERS = {
  LOW_IMAGE_CONFIDENCE: {
    factor: 1.3,   // 30% more cautious when image quality is low
    label: 'Low image confidence — applying caution multiplier',
  },
  DVA_QUANTITY_WARNING: {
    factor: 1.1,   // 10% more cautious for unusual quantities
    label: 'Unusual quantity detected — applying minor caution',
  },
  DVA_FUTURE_PREP_WARNING: {
    factor: 1.2,   // 20% more cautious for future prep times
    label: 'Future preparation time — applying temporal caution',
  },
  DEGRADED_IMAGE: {
    factor: 1.5,   // 50% more cautious when image analysis degraded
    label: 'Image analysis degraded — applying high caution multiplier',
  },
};

class RiskModelingAgent {
  static AGENT_ID = 'RMA';

  /**
   * Calculate comprehensive risk assessment
   * @param {Object} validatedData - Clean data from DVA { quantity, category, preparationTime, costPerMeal, ... }
   * @param {Array} dvaWarnings - Warnings generated by the DVA
   * @param {Object} imageAnalysis - Analysis result from VAA { qualityScore, confidenceLevel, degraded, ... }
   * @param {AgentLogger} logger - Agent audit logger
   * @returns {{ success: boolean, data: Object|null, warnings: Array }}
   */
  static calculate(validatedData, dvaWarnings, imageAnalysis, logger) {
    logger.log(this.AGENT_ID, 'START', 'Beginning risk modeling with multi-agent inputs.');

    const warnings = [];

    try {
      // ── Step 1: Baseline Risk Calculation ─────────────
      const { category, preparationTime, quantity, costPerMeal } = validatedData;
      const safeHours = SAFE_WINDOWS[category] || SAFE_WINDOWS.other;
      const prepTime = new Date(preparationTime);
      const expiryTime = new Date(prepTime.getTime() + safeHours * 60 * 60 * 1000);

      const now = new Date();
      const baseHoursRemaining = (expiryTime - now) / (1000 * 60 * 60);

      logger.log(this.AGENT_ID, 'INFO', `Baseline: ${category} has ${safeHours}h safe window. ${baseHoursRemaining.toFixed(2)}h remaining.`, {
        category,
        safeWindowHours: safeHours,
        baseHoursRemaining: baseHoursRemaining.toFixed(2),
      });

      // ── Step 2: Apply Risk Modifiers (Agent Intelligence) ─
      let adjustedHoursRemaining = baseHoursRemaining;
      const appliedModifiers = [];

      // Modifier A: Low image confidence reduces remaining time perception
      if (imageAnalysis && imageAnalysis.qualityScore < 0.5) {
        const modifier = imageAnalysis.degraded
          ? RISK_MODIFIERS.DEGRADED_IMAGE
          : RISK_MODIFIERS.LOW_IMAGE_CONFIDENCE;

        adjustedHoursRemaining = adjustedHoursRemaining / modifier.factor;
        appliedModifiers.push({
          type: imageAnalysis.degraded ? 'DEGRADED_IMAGE' : 'LOW_IMAGE_CONFIDENCE',
          factor: modifier.factor,
          label: modifier.label,
          reason: `Image quality score: ${imageAnalysis.qualityScore}`,
        });

        logger.log(this.AGENT_ID, 'DECISION', modifier.label, {
          factor: modifier.factor,
          qualityScore: imageAnalysis.qualityScore,
        });
      }

      // Modifier B: DVA quantity warnings
      const quantityWarning = dvaWarnings.find(w => w.field === 'quantity');
      if (quantityWarning) {
        const modifier = RISK_MODIFIERS.DVA_QUANTITY_WARNING;
        adjustedHoursRemaining = adjustedHoursRemaining / modifier.factor;
        appliedModifiers.push({
          type: 'DVA_QUANTITY_WARNING',
          factor: modifier.factor,
          label: modifier.label,
          reason: quantityWarning.message,
        });

        logger.log(this.AGENT_ID, 'DECISION', modifier.label, {
          factor: modifier.factor,
          originalWarning: quantityWarning.message,
        });
      }

      // Modifier C: Future preparation time warnings
      const futureWarning = dvaWarnings.find(w => w.field === 'preparationTime');
      if (futureWarning) {
        const modifier = RISK_MODIFIERS.DVA_FUTURE_PREP_WARNING;
        adjustedHoursRemaining = adjustedHoursRemaining / modifier.factor;
        appliedModifiers.push({
          type: 'DVA_FUTURE_PREP_WARNING',
          factor: modifier.factor,
          label: modifier.label,
          reason: futureWarning.message,
        });

        logger.log(this.AGENT_ID, 'DECISION', modifier.label, {
          factor: modifier.factor,
          originalWarning: futureWarning.message,
        });
      }

      // ── Step 3: Final Risk Level Determination ────────
      const hoursRemaining = Math.max(0, parseFloat(adjustedHoursRemaining.toFixed(2)));

      let riskLevel;
      if (hoursRemaining >= 3) {
        riskLevel = 'LOW';
      } else if (hoursRemaining >= 1) {
        riskLevel = 'MEDIUM';
      } else {
        riskLevel = 'HIGH';
      }

      // Check if modifiers shifted the risk level
      let baseRiskLevel;
      const baseHR = Math.max(0, baseHoursRemaining);
      if (baseHR >= 3) baseRiskLevel = 'LOW';
      else if (baseHR >= 1) baseRiskLevel = 'MEDIUM';
      else baseRiskLevel = 'HIGH';

      if (riskLevel !== baseRiskLevel && appliedModifiers.length > 0) {
        logger.log(this.AGENT_ID, 'DECISION', `Risk level adjusted from ${baseRiskLevel} to ${riskLevel} due to ${appliedModifiers.length} modifier(s).`);
        warnings.push({
          field: 'riskLevel',
          message: `Risk level was elevated from ${baseRiskLevel} to ${riskLevel} based on cross-agent intelligence.`,
        });
      }

      // ── Step 4: Cost Estimation ───────────────────────
      const cost = Math.round(parsedCostPerMeal(costPerMeal) * 100) / 100;
      const qty = parseInt(quantity) || 0;
      const costEstimate = {
        costPerMeal: cost,
        totalValue: Math.round(qty * cost * 100) / 100,
      };

      // ── Step 5: Assemble Result ───────────────────────
      const result = {
        riskLevel,
        expiryTime,
        hoursRemaining,
        safeWindowHours: safeHours,
        baseHoursRemaining: Math.max(0, parseFloat(baseHoursRemaining.toFixed(2))),
        riskModifiers: appliedModifiers,
        modifierCount: appliedModifiers.length,
        costEstimate,
        requiresHumanReview: imageAnalysis?.degraded || hoursRemaining < 0.5 || imageAnalysis?.qualityScore < 0.4,
      };

      logger.log(this.AGENT_ID, 'SUCCESS', `Risk modeling complete: ${riskLevel} risk, ${hoursRemaining}h remaining, ${appliedModifiers.length} modifier(s) applied.`, {
        riskLevel,
        hoursRemaining,
        modifierCount: appliedModifiers.length,
        requiresHumanReview: result.requiresHumanReview,
      });

      return {
        success: true,
        data: result,
        warnings,
      };

    } catch (error) {
      logger.log(this.AGENT_ID, 'FAILURE', `Risk calculation failed: ${error.message}`);
      throw new AgentError(
        this.AGENT_ID,
        `Risk modeling failed: ${error.message}`,
        AgentError.CODES.RISK_CALCULATION_FAILED,
        { originalError: error.message }
      );
    }
  }
}

/**
 * Safe cost parser
 */
function parsedCostPerMeal(value) {
  const parsed = parseFloat(value);
  return isNaN(parsed) ? 0 : parsed;
}

module.exports = RiskModelingAgent;
